
  --Q1. What is the total revenue generated by male vs. female customers?

  sql```
  select gender, SUM(purchase_amount) as revenue
  from customer
  group by gender;
  ```
  
  --Q2. Which customers used a discount but still spent more than the average purchase amount?

  sql```
  select customer_id, purchase_amount
  from customer
  where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)from customer);
   ```
  
  --Q3. Which are the top 5 products with the highest average review rating?

  sql```
  select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
  from customer
  group by item_purchased
  order by avg(review_rating) desc
  limit 10;
  ```
  
  --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

  sql```
  select shipping_type,
  ROUND(AVG(purchase_amount),2)
  from customer
  where shipping_type in ('Standard','Express')
  group by shipping_type;
  ```

  --Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

  sql```
  select subscription_status,
  count(customer_id) as total_customers,
  round(avg(purchase_amount),2) as avg_spend,
  round(sum(purchase_amount),2) as total_revenue
  from customer
  group by subscription_status
  order by total_revenue, avg_spend DESC;
  ```
  
  --Q6. Which 5 products have the highest percentage of purchases with discounts applied?

  sql```
  select item_purchased,
  ROUND(100 * SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
  from customer
  group by item_purchased
  order by discount_rate desc
  limit 5;
  ```


  --07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

  sql```
  with customer_type as(
  SELECT customer_id, previous_purchases,
  CASE 
      WHEN previous_purchases = 1 then 'New'
	  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	  ELSE 'Loyal'
	  END AS customer_segment
  from customer
 )
 
  SELECT customer_segment, COUNT(*) AS "No_of_customers"
  from customer_type
  group by customer_segment;
  ```

 --Q8. What are the top 3 most purchased products within each category?

 sql```
 WITH item_counts AS (
 SELECT category,
 item_purchased,
 COUNT(customer_id) AS total_orders,
 ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT (customer_id)DESC) AS item_rank
 FROM customer
 GROUP BY category, item_purchased
 )

 SELECT item_rank, category, item_purchased, total_orders
 FROM item_counts
 WHERE item_rank <= 3;
 ```

  --09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

  sql```
  select subscription_status,
  count(customer_id) AS "repeat_buyers"
  from customer
  where previous_purchases > 5
  group by subscription_status;
  ```
  
  --Q10. What is the revenue contribution of each age group?

  sql```
  select age_group,
  sum(purchase_amount) as total_revenue
  from customer
  group by age_group
  order by total_revenue DESC;
  ```

  
